version: "3.9"
services:
  database:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "server"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data: